[mypy]
python_version = 3.12
ignore_missing_imports = True
follow_imports = silent
warn_unused_ignores = False
warn_redundant_casts = False
allow_redefinition = True
exclude = (\.venv.*|__pycache__|tests/golden|build|dist)
